// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://pfuuzrkbqypcsjcqmizj.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmdXV6cmticXlwY3NqY3FtaXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjkyMzksImV4cCI6MjA2NDUwNTIzOX0.u34yL0O-rWlGrc0354ezdw-vZfGm5DzU5-8JGw-znG0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
