// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qunrljxtjzdrxkzbbkbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1bnJsanh0anpkcnhremJia2J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODc3ODUsImV4cCI6MjA2ODY2Mzc4NX0.hb2_zFdhemVFGkj0HerpghcKefMpnK8AU7Q-3bSHkHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});